name: build and push production client to dockerhub

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            "REACT_APP_GRAPHQL_API_URL=https://pierre.wns.wilders.dev/graphql"
          context: "{{defaultContext}}:client"
          file: "Dockerfile.production"
          tags: ${{ inputs.image_name }}
