name: integration-tests

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        run: |
          echo JWT_PRIVATE_KEY=zeyfgzeigfyzegfyuzegf >> .env
          echo NODE_ENV=development >> .env
          echo CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:4000,http://192.168.1.7:4000 >> .env
          echo SERVER_HOST=localhost >> .env
          echo SERVER_PORT=4000 >> .env
          echo DB_HOST=localhost >> .env
      - name: Run integration test
        run: npm run integration-tests
