name: integration-tests

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        run: |
          echo JWT_PRIVATE_KEY=zeyfgzeigfyzegfyuzegf >> ./server/.env

      - name: Run integration test
        run: npm run integration-tests
